name: Build

on:
  push:
  pull_request:

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pre-commit
          key: ${{ runner.os }}-pip-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install pre-commit and helpers
        run: |
          pip install pre-commit compiledb configuredb buildcache
          pre-commit install --install-hooks
      - name: Run pre-commit
        run: pre-commit run --show-diff-on-failure

  clang-build:
    needs: precommit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Clang and build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang ninja-build cmake
      - name: Configure
        run: CC=clang cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_STANDARD=23 -DLLVM_ENABLE_LTO=ON
      - name: Build
        run: ninja -C build
