name: Build

on:
  push:
  pull_request:

jobs:
  gcc-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential gcc-multilib
      - name: Build with GCC C23 x86_64
        run: make -C usr/src CC=gcc CSTD=-std=c2x CFLAGS_EXTRA='-m64'
      - name: Generate file inventory
        run: make inventory
      - name: Upload inventory
        uses: actions/upload-artifact@v3
        with:
          name: file-inventory-${{ github.job }}
          path: docs/file_inventory.txt

  gcc-i686:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential gcc-multilib
      - name: Build with GCC C23 i686
        run: make -C usr/src CC=gcc CSTD=-std=c2x CFLAGS_EXTRA='-m32'
      - name: Generate file inventory
        run: make inventory
      - name: Upload inventory
        uses: actions/upload-artifact@v3
        with:
          name: file-inventory-${{ github.job }}
          path: docs/file_inventory.txt

  clang-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Clang
        run: sudo apt-get update && sudo apt-get install -y clang make gcc-multilib
      - name: Build with Clang C23 x86_64
        run: make -C usr/src CC=clang CSTD=-std=c2x CFLAGS_EXTRA='-m64'
      - name: Generate file inventory
        run: make inventory
      - name: Upload inventory
        uses: actions/upload-artifact@v3
        with:
          name: file-inventory-${{ github.job }}
          path: docs/file_inventory.txt

  clang-i686:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Clang
        run: sudo apt-get update && sudo apt-get install -y clang make gcc-multilib
      - name: Build with Clang C23 i686
        run: make -C usr/src CC=clang CSTD=-std=c2x CFLAGS_EXTRA='-m32'
      - name: Generate file inventory
        run: make inventory
      - name: Upload inventory
        uses: actions/upload-artifact@v3
        with:
          name: file-inventory-${{ github.job }}
          path: docs/file_inventory.txt
