name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential clang cmake ninja-build
      - name: Configure
        run: |
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            CC=gcc
            CXX=g++
          else
            CC=clang
            CXX=clang++
          fi
          cmake -S . -B build -G Ninja -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX
      - name: Build
        run: cmake --build build
