name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build bison flex
      - name: Configure
        run: |
          cmake -S . -B build -G Ninja \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_STANDARD=23 \
                -DCMAKE_C_FLAGS='-O3' \
                -DLLVM_ENABLE_LTO=ON
      - name: Build
        run: ninja -C build
